apiVersion: apps/v1
kind: Deployment
metadata:
  name: cometweb
spec:
  selector:
    matchLabels:
      app: cometweb
  replicas: 1
  template:
    metadata:
      labels:
        app: cometweb
    spec:
      containers:
        - name: cometweb
          image: doitcomet/cicdtest:blue
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cometweb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: cometweb
